% Title: Baseline VAR using Local Projections
% Objective: Quarterly and Annual VAR analysis to establish whether including
% inequality/distribution matters for aggregates. Following Kliensen et al 2018 "The
% Nonlinear Effects of Uncertainty Shocks."
% Author: Nisha Chikhale
% Date Created: 03/30/2020
% Date Modified: 04/06/2020
%% 
clc;
clear;
set(groot,'defaultLineLineWidth',2.0) % set line width thicker

%% Download data from FRED %%
% The sample in JKO is 1985-2018 quarterly, I do 1985-present quarterly
url = "https://fred.stlouisfed.org/";
c = fred(url);

series1 = "GDPC1"; % real GDP quarterly data
startdate1 = '09/01/1984'; 
enddate1 = '06/01/2019'; 

d1 = fetch(c,series1,startdate1,enddate1);
d2 = getFredData('PCE','1984-09-01','2019-06-01', [],'q'); 
d3 = getFredData('PAYEMS','1984-09-01','2019-06-01', [],'q'); 
d4 = getFredData('FEDFUNDS','1984-09-01','2019-06-01', [],'q'); 
d5 = getFredData('DGS10','1984-09-01','2019-06-01', [],'q');
%fetch doesn't work when you need to change the frequency of data

gdpc1 = d1.Data(1:139,2);
N = size(gdpc1,1);
price = d2.Data(1:139,2);
emp = d3.Data(2:139,2);
empt1 = d3.Data(1:138,2);
ffr = d4.Data(2:139,2);
tyield = d5.Data(2:139,2);

close(c)
%% Compute annualized GDP growth and inflation rate %%
gdpt = gdpc1(2:N,1);
gdpt1 = gdpc1(1:N-1,1);
yt = 400*log(gdpt./gdpt1); %annualized gdp growth
pcet = price(2:N,1);
pcet1 = price(1:N-1,1);
inft = 400*log(pcet./pcet1); %annualized inflation rate

%% compute log of first differences of variables and annualize GDP, P and Emp
 x1 = (log(gdpt) - log(gdpt1))*400;
 x2 = (log(pcet) - log(pcet1))*400;
 x3 = (log(emp) - log(empt1))*400;
 x4 = ffr; %in levels
 x5 = tyield; %in levels

%% Download JLN uncertainty data %%

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nishachikhale/Documents/Stata/Ludvigsondownload/MacroFinanceUncertainty_201908_update/MacroUncertaintyToCirculate.xlsx
%    Worksheet: Macro Uncertainty
%
% Auto-generated by MATLAB on 13-Mar-2020 12:57:22

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Macro Uncertainty";
opts.DataRange = "A2:D709";

% Specify column names and types
opts.VariableNames = ["Date", "h1", "h3", "h12"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Date", "InputFormat", "");

% Import the data
MacroUncertaintyToCirculate = readtable("/Users/nishachikhale/Documents/Stata/Ludvigsondownload/MacroFinanceUncertainty_201908_update/MacroUncertaintyToCirculate.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nishachikhale/Documents/Stata/Ludvigsondownload/MacroFinanceUncertainty_201908_update/FinancialUncertaintyToCirculate.xlsx
%    Worksheet: Financial Uncertainty
%
% Auto-generated by MATLAB on 13-Mar-2020 12:57:46

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Financial Uncertainty";
opts.DataRange = "A2:D709";

% Specify column names and types
opts.VariableNames = ["Date", "h1", "h3", "h12"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Date", "InputFormat", "");

% Import the data
FinancialUncertaintyToCirculate = readtable("/Users/nishachikhale/Documents/Stata/Ludvigsondownload/MacroFinanceUncertainty_201908_update/FinancialUncertaintyToCirculate.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%% Create uncertainty variables %%
um_q = table2array(MacroUncertaintyToCirculate(295:3:708,3));%grab every 3rd element in 3rd column to get quarterly macro uncertainty at h=3
uf_q = table2array(FinancialUncertaintyToCirculate(295:3:708,3));

%% Download EPU data %%
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nishachikhale/Documents/MATLAB/ECON718/StateDependenceofAggUncertainty/RawData/EPU/quarterly_epu_clean.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 24-Mar-2020 08:33:08

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:F142";

% Specify column names and types
opts.VariableNames = ["newyear", "month", "three_component_index", "epu", "quarter", "year"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Import the data
quarterlyepuclean = readtable("/Users/nishachikhale/Documents/MATLAB/ECON718/StateDependenceofAggUncertainty/RawData/EPU/quarterly_epu_clean.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%% Create EPU uncertianty variables %% 1985q1:2019q2
epu_q = table2array(quarterlyepuclean(1:138,4));

%% Baseline VAR 1.0 %%
%% Choose optimal lag length %%
L = length(x1);
for k=1:4
        Mdl = varm(6,k);
        Input = [epu_q(k:L,1) x1(k:L,1) x2(k:L,1) x3(k:L,1) x4(k:L,1) x5(k:L,1) ];  %Input = [um_q(k:N,1) yt(k:N,1) inft(k:N,1) emp(k:N,1) ffr(k:N,1) tyield(k:N,1) uf_q(k:N,1)]; 
        EstMdl = estimate(Mdl,Input);
        Results = summarize(EstMdl);
        BICtable(k) = Results.BIC;
        AICtable(k) = Results.AIC;
end
  
AICtable
BICtable


L = length(x1);
for k=1:4
        Mdl2 = varm(7,k);
        Input2 = [um_q(k:L,1) x1(k:L,1) x2(k:L,1) x3(k:L,1) x4(k:L,1) x5(k:L,1) uf_q(k:L,1)];  %Input = [um_q(k:N,1) yt(k:N,1) inft(k:N,1) emp(k:N,1) ffr(k:N,1) tyield(k:N,1) uf_q(k:N,1)]; 
        EstMdl2 = estimate(Mdl2,Input2);
        Results2 = summarize(EstMdl2);
        BICtable2(k) = Results2.BIC;
        AICtable2(k) = Results2.AIC;
end
  
AICtable2
BICtable2

disp("Let lag length be 1 by BIC")


% parameters 
p = 1;  %number of lags
n = 6;  %number of vars 
N = length(epu_q)-1; 
H = 12;
% parameters for IRFs
time = linspace(0,12,12);
quarters = time;
%% Compute IRFs via LP %%
 %% IRFs via 13 OLS regressions
 trend = cumsum(ones(N,1));
% Local projection

for i = 1:H+1 % 0 to H
    X1 = [ones(N-i,1) trend(1:N-i,1) epu_q(1:N-i,1)]; %shock
    X2 = [ones(N-i,1) trend(1:N-i,1) epu_q(1+1:N-i+1,1) x1(1:N-i,:)]; % shock and lagged x1
    X3 = [ones(N-i,1) trend(1:N-i,1) epu_q(1+1:N-i+1,1) x1(1:N-i,:) x2(1:N-i,:)];
    X4 = [ones(N-i,1) trend(1:N-i,1) epu_q(1+1:N-i+1,1) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:)];
    X5 = [ones(N-i,1) trend(1:N-i,1) epu_q(1+1:N-i+1,1) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:)];
    X6 = [ones(N-i,1) trend(1:N-i,1) epu_q(1+1:N-i+1,1) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:) x5(1:N-i,:)] ; % matrix of regressors
    Y1 = [epu_q(i:N-1,:)]; % resize Y
    Y2 = [x1(i+1:N,:)];
    Y3 = [x2(i+1:N,:)];
    Y4 = [x3(i+1:N,:)];
    Y5 = [x4(i+1:N,:)];
    Y6 = [x5(i+1:N,:)]; %[x5(i+1:N,:)]
    beta1epu(i,:)= X1\Y1; % record OLS estimators
    beta1x1(i,:)= X2\Y2;
    beta1x2(i,:)= X3\Y3;
    beta1x3(i,:)= X4\Y4;
    beta1x4(i,:)= X5\Y5;
    beta1x5(i,:)= X6\Y6;
end
% Normailize IRFs by size of the shock
%so that the IRFs capture the response of a 1% positive shock
IRF_epu = beta1epu(1,3)\beta1epu(:,3);%shock is 3rd in the matrix
IRF_x1 = beta1epu(1,3)\beta1x1(:,3);
IRF_x2 = beta1epu(1,3)\beta1x2(:,3);
IRF_x3 = beta1epu(1,3)\beta1x3(:,3);
IRF_x4 = beta1epu(1,3)\beta1x4(:,3);
IRF_x5 = beta1epu(1,3)\beta1x5(:,3);

%plot irf unsmoothed
figure(1)
cla
plot(quarters, IRF_epu(1:12,1)) %epu uncertainty
hold on
plot(quarters, IRF_x1(1:12,1)) %gdp growth
hold on
plot(quarters, IRF_x2(1:12,1)) %inflation rate
hold on
plot(quarters, IRF_x3(1:12,1)) %employment rate
hold on
plot(quarters, IRF_x4(1:12,1)) %ffr
hold on
plot(quarters, IRF_x5(1:12,1)) %tbill yield
title('IRF: Response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
legend('EPU','GDP growth','Inf','Emp','FFR','Tbill yield')
hold off


% smooth IRF to shocks
IRF_epu_s = [IRF_epu(1); zeros(H-1,1); IRF_epu(end)];
IRF_x1_s = [IRF_x1(1); zeros(H-1,1); IRF_x1(end)];
IRF_x2_s = [IRF_x2(1); zeros(H-1,1); IRF_x2(end)];
IRF_x3_s = [IRF_x3(1); zeros(H-1,1); IRF_x3(end)];
IRF_x4_s = [IRF_x4(1); zeros(H-1,1); IRF_x4(end)];
IRF_x5_s = [IRF_x5(1); zeros(H-1,1); IRF_x5(end)];
for i = 2:H
IRF_epu_s(i) = mean(IRF_epu(i-1:i+1));
IRF_x1_s(i) = mean(IRF_x1(i-1:i+1));
IRF_x2_s(i) = mean(IRF_x2(i-1:i+1));
IRF_x3_s(i) = mean(IRF_x3(i-1:i+1));
IRF_x4_s(i) = mean(IRF_x4(i-1:i+1));
IRF_x5_s(i) = mean(IRF_x5(i-1:i+1));
end

%plot individual irfs, smoothed
figure(2)
cla 
plot(quarters, IRF_epu_s(1:12,1)) %epu uncertainty
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation EPU uncertainty')
legend('EPU')
hold off
saveas(figure(2),[pwd '/plots/jko/lp_v1_epushock.png']);
figure(3)
cla 
plot(quarters, IRF_x1_s(1:12,1)) %gdp growth
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized GDP growth')
legend('GDP')
hold off
saveas(figure(3),[pwd '/plots/jko/lp_v2_epushock.png']);
figure(4)
cla 
plot(quarters, IRF_x2_s(1:12,1)) %inflation rate
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized Inflation')
legend('PCE')
hold off
saveas(figure(4),[pwd '/plots/jko/lp_v3_epushock.png']);
figure(5)
cla 
plot(quarters, IRF_x3_s(1:12,1)) %employment rate
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized Employment')
legend('Emp')
hold off
saveas(figure(5),[pwd '/plots/jko/lp_v4_epushock.png']);
figure(6)
cla 
plot(quarters, IRF_x4_s(1:12,1)) %ffr
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Federal Funds rate')
legend('FFR')
hold off
saveas(figure(6),[pwd '/plots/jko/lp_v5_epushock.png']);
figure(7)
cla 
plot(quarters, IRF_x5_s(1:12,1)) %tbill
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Tbill yield')
legend('Tbill yield')
hold off
saveas(figure(7),[pwd '/plots/jko/lp_v6_epushock.png']);





%% VAR 2.0 w/ inequality %%
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nishachikhale/Documents/MATLAB/ECON718/StateDependenceofAggUncertainty/RawData/DFA_FRB/dfa-9050ratio-clean.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 21-Mar-2020 11:22:35

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:H123";

% Specify column names and types
opts.VariableNames = ["date1", "a", "b", "bottom", "year", "Q", "top", "ratio"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "date1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "date1", "EmptyFieldRule", "auto");

% Import the data
dfa9050ratioclean = readtable("/Users/nishachikhale/Documents/MATLAB/ECON718/StateDependenceofAggUncertainty/RawData/DFA_FRB/dfa-9050ratio-clean.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%% Create in sample 1989Q3:2019Q2 %%
ratio = table2array(dfa9050ratioclean(1:120,8));
epu_q = epu_q(19:138,1);
x1 = x1(19:138,1);
x2 = x2(19:138,1);
x3 = x3(19:138,1);
x4 = x4(19:138,1);
x5 = x5(19:138,1);


%let the optimal lag length be the same as in VAR 1.0  
% parameters 
p = 1;  %number of lags
n = 7;  %number of vars 
N = length(epu_q)-1; %update N

%% Compute IRFs via LP %%
 %% IRFs via 13 OLS regressions
 trend = cumsum(ones(N,1));
% Local projection

for i = 1:H+1 % 0 to H
    X1 = [ones(N-i,1) trend(1:N-i,1) epu_q(1:N-i,1)]; %shock
    X2 = [ones(N-i,1) trend(1:N-i,1) epu_q(2:N-i+1) ratio(1:N-i,:)]; %lagged ratio
    X3 = [ones(N-i,1) trend(1:N-i,1) epu_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) ];
    X4 = [ones(N-i,1) trend(1:N-i,1) epu_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:)];
    X5 = [ones(N-i,1) trend(1:N-i,1) epu_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:)];
    X6 = [ones(N-i,1) trend(1:N-i,1) epu_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:)];
    X7 = [ones(N-i,1) trend(1:N-i,1) epu_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:) x5(1:N-i,:)] ; % matrix of regressors
    Y1 = [epu_q(i:N-1,:)]; % resize Y
    Y2 = [ratio(i+1:N,:)];
    Y3 = [x1(i+1:N,:)];
    Y4 = [x2(i+1:N,:)];
    Y5 = [x3(i+1:N,:)];
    Y6 = [x4(i+1:N,:)];
    Y7 = [x5(i+1:N,:)];
    beta2epu(i,:)= X1\Y1; % record OLS estimators
    beta2ratio(i,:)= X2\Y2;
    beta2x1(i,:)= X3\Y3;
    beta2x2(i,:)= X4\Y4;
    beta2x3(i,:)= X5\Y5;
    beta2x4(i,:)= X6\Y6;
    beta2x5(i,:)= X7\Y7;
end

% Normailize IRFs by size of the shock
%so that the IRFs capture the response of a 1% positive shock
IRF2_epu = beta2epu(1,3)\beta2epu(:,3);%shock is 3rd in the matrix
IRF2_ratio = beta2epu(1,3)\beta2ratio(:,3);
IRF2_x1 = beta2epu(1,3)\beta2x1(:,3);
IRF2_x2 = beta2epu(1,3)\beta2x2(:,3);
IRF2_x3 = beta2epu(1,3)\beta2x3(:,3);
IRF2_x4 = beta2epu(1,3)\beta2x4(:,3);
IRF2_x5 = beta2epu(1,3)\beta2x5(:,3);

%plot irf unsmoothed
figure(8)
cla
plot(quarters, IRF2_epu(1:12,1)) %epu uncertainty
hold on
plot(quarters, IRF2_ratio(1:12,1)) %inequality
hold on
plot(quarters, IRF2_x1(1:12,1)) %gdp growth
hold on
plot(quarters, IRF2_x2(1:12,1)) %inflation rate
hold on
plot(quarters, IRF2_x3(1:12,1)) %employment rate
hold on
plot(quarters, IRF2_x4(1:12,1)) %ffr
hold on
plot(quarters, IRF2_x5(1:12,1)) %tbill yield
title('IRF: Response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
legend('EPU','90/50 ratio','GDP growth','Inf','Emp','FFR','Tbill yield')
hold off


% smooth IRF to shocks
IRF2_epu_s = [IRF2_epu(1); zeros(H-1,1); IRF2_epu(end)];
IRF2_ratio_s = [IRF2_ratio(1); zeros(H-1,1); IRF2_ratio(end)];
IRF2_x1_s = [IRF2_x1(1); zeros(H-1,1); IRF2_x1(end)];
IRF2_x2_s = [IRF2_x2(1); zeros(H-1,1); IRF2_x2(end)];
IRF2_x3_s = [IRF2_x3(1); zeros(H-1,1); IRF2_x3(end)];
IRF2_x4_s = [IRF2_x4(1); zeros(H-1,1); IRF2_x4(end)];
IRF2_x5_s = [IRF2_x5(1); zeros(H-1,1); IRF2_x5(end)];
for i = 2:H
IRF2_epu_s(i) = mean(IRF2_epu(i-1:i+1));
IRF2_ratio_s(i) = mean(IRF2_ratio(i-1:i+1));
IRF2_x1_s(i) = mean(IRF2_x1(i-1:i+1));
IRF2_x2_s(i) = mean(IRF2_x2(i-1:i+1));
IRF2_x3_s(i) = mean(IRF2_x3(i-1:i+1));
IRF2_x4_s(i) = mean(IRF2_x4(i-1:i+1));
IRF2_x5_s(i) = mean(IRF2_x5(i-1:i+1));
end

%plot individual irfs smoothed
figure(9)
cla 
plot(quarters, IRF2_epu_s(1:12,1)) %epu uncertainty
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation EPU uncertainty')
legend('EPU')
hold off
saveas(figure(9),[pwd '/plots/jko/lp2_v1_epushock.png']);
figure(10)
cla 
plot(quarters, IRF2_ratio_s(1:12,1)) %inequality
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation 90/50 ratio')
legend('90/50 ratio')
hold off
saveas(figure(10),[pwd '/plots/jko/lp2_v2_epushock.png']);
figure(11)
cla 
plot(quarters, IRF2_x1_s(1:12,1)) %gdp growth
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized GDP growth')
legend('GDP')
hold off
saveas(figure(11),[pwd '/plots/jko/lp2_v3_epushock.png']);
figure(12)
cla 
plot(quarters, IRF2_x2_s(1:12,1)) %inflation rate
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized Inflation')
legend('PCE')
hold off
saveas(figure(12),[pwd '/plots/jko/lp2_v4_epushock.png']);
figure(13)
cla 
plot(quarters, IRF2_x3_s(1:12,1)) %employment rate
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Employment rate')
legend('EMP')
hold off
saveas(figure(13),[pwd '/plots/jko/lp2_v5_epushock.png']);
figure(14)
cla 
plot(quarters, IRF2_x4_s(1:12,1)) %ffr
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Federal Funds rate')
legend('FFR')
hold off
saveas(figure(14),[pwd '/plots/jko/lp2_v6_epushock.png']);
figure(15)
cla 
plot(quarters, IRF2_x5_s(1:12,1)) %tbill
title('IRF: Smoothed response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Tbill yield')
legend('Tbill yield')
hold off
saveas(figure(15),[pwd '/plots/jko/lp2_v7_epushock.png']);





%% VAR 3.0 w/ inequality and JLN uncertainty %%
%% Create uncertainty in smaple 1989Q3:2019Q2 %%
um_q = table2array(MacroUncertaintyToCirculate(349:3:708,3)); 
uf_q = table2array(FinancialUncertaintyToCirculate(349:3:708,3));

%let the optimal lag length be the same as in VAR 1.0  
% parameters 
p = 1;  %number of lags
n = 8;  %number of vars 
N = length(um_q)-1; %update N

%% Compute IRFs via LP %%
 %% IRFs via 13 OLS regressions
 trend = cumsum(ones(N,1));
% Local projection
for i = 1:H+1 % 0 to H
    X1 = [ones(N-i,1) trend(1:N-i,1) um_q(1:N-i,1)] ; %shock
    X2 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) ratio(1:N-i,:)] ; % no um_q 
    X3 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:)] ; 
    X4 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:)] ;
    X5 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:)] ;
    X6 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:)] ;
    X7 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:) x5(1:N-i,:)] ;
    X8 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) ratio(1:N-i,:) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:) x5(1:N-i,:) uf_q(1:N-i,:)] ; % matrix of regressors
    Y1 = [um_q(i:N-1,:)]; % resize Y--[um_q(i+2:N+1,:)];
    Y2 = [ratio(i+1:N,:)];
    Y3 = [x1(i+1:N,:)];
    Y4 = [x2(i+1:N,:)];
    Y5 = [x3(i+1:N,:)];
    Y6 = [x4(i+1:N,:)];
    Y7 = [x5(i+1:N,:)];
    Y8 = [uf_q(i+1:N,:)];
    beta3um(i,:)= X1\Y1; % record OLS estimators
    beta3ratio(i,:)= X2\Y2;
    beta3x1(i,:)= X3\Y3;
    beta3x2(i,:)= X4\Y4;
    beta3x3(i,:)= X5\Y5;
    beta3x4(i,:)= X6\Y6;
    beta3x5(i,:)= X7\Y7;
    beta3uf(i,:)= X8\Y8;
end

% Normailize IRFs by size of the shock
%so that the IRFs capture the response of a 1% positive shock
IRF3_um = beta3um(1,3)\beta3um(:,3);%shock is 3rd in the matrix
IRF3_ratio = beta3um(1,3)\beta3ratio(:,3);
IRF3_x1 = beta3um(1,3)\beta3x1(:,3);
IRF3_x2 = beta3um(1,3)\beta3x2(:,3);
IRF3_x3 = beta3um(1,3)\beta3x3(:,3);
IRF3_x4 = beta3um(1,3)\beta3x4(:,3);
IRF3_x5 = beta3um(1,3)\beta3x5(:,3);
IRF3_uf = beta3um(1,3)\beta3uf(:,3);


%plot irf unsmoothed
figure(16)
cla
plot(quarters, IRF3_um(1:12,1)) %macro uncertainty
hold on
plot(quarters, IRF3_ratio(1:12,1)) %inequality
hold on
plot(quarters, IRF3_x1(1:12,1)) %gdp growth
hold on
plot(quarters, IRF3_x2(1:12,1)) %inflation rate
hold on
plot(quarters, IRF3_x3(1:12,1)) %employment rate
hold on
plot(quarters, IRF3_x4(1:12,1)) %ffr
hold on
plot(quarters, IRF3_x5(1:12,1)) %tbill yield
hold on
plot(quarters, IRF3_uf(1:12,1)) %financial uncertainty
title('IRF: Response to a 1% EPU Uncertainty Shock')
xlabel('Time in quarters')
legend('Macro uncertianty','90/50 ratio','GDP growth','Inf','Emp','FFR','Tbill yield','Financial uncertainty')
hold off

% smooth IRF to shocks
IRF3_um_s = [IRF3_um(1); zeros(H-1,1); IRF3_um(end)];
IRF3_ratio_s = [IRF3_ratio(1); zeros(H-1,1); IRF3_ratio(end)];
IRF3_x1_s = [IRF3_x1(1); zeros(H-1,1); IRF3_x1(end)];
IRF3_x2_s = [IRF3_x2(1); zeros(H-1,1); IRF3_x2(end)];
IRF3_x3_s = [IRF3_x3(1); zeros(H-1,1); IRF3_x3(end)];
IRF3_x4_s = [IRF3_x4(1); zeros(H-1,1); IRF3_x4(end)];
IRF3_x5_s = [IRF3_x5(1); zeros(H-1,1); IRF3_x5(end)];
IRF3_uf_s = [IRF3_uf(1); zeros(H-1,1); IRF3_uf(end)];
for i = 2:H
IRF3_um_s(i) = mean(IRF3_um(i-1:i+1));
IRF3_ratio_s(i) = mean(IRF3_ratio(i-1:i+1));
IRF3_x1_s(i) = mean(IRF3_x1(i-1:i+1));
IRF3_x2_s(i) = mean(IRF3_x2(i-1:i+1));
IRF3_x3_s(i) = mean(IRF3_x3(i-1:i+1));
IRF3_x4_s(i) = mean(IRF3_x4(i-1:i+1));
IRF3_x5_s(i) = mean(IRF3_x5(i-1:i+1));
IRF3_uf_s(i) = mean(IRF3_uf(i-1:i+1));
end

%plot individual irfs smoothed
figure(17)
cla 
plot(quarters, IRF3_um_s(1:12,1)) %macro uncertainty
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Macro uncertainty')
legend('Macro uncertainty')
hold off
saveas(figure(17),[pwd '/plots/jko/lp3_v1_umshock.png']);
figure(18)
cla 
plot(quarters, IRF3_ratio_s(1:12,1)) %inequality
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation 90/50 ratio')
legend('90/50 ratio')
hold off
saveas(figure(18),[pwd '/plots/jko/lp3_v2_umshock.png']);
figure(19)
cla 
plot(quarters, IRF3_x1_s(1:12,1)) %gdp growth
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized GDP growth')
legend('GDP')
hold off
saveas(figure(19),[pwd '/plots/jko/lp3_v3_umshock.png']);
figure(20)
cla 
plot(quarters, IRF3_x2_s(1:12,1)) %inflation rate
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized Inflation')
legend('PCE')
hold off
saveas(figure(20),[pwd '/plots/jko/lp3_v4_umshock.png']);
figure(21)
cla 
plot(quarters, IRF3_x3_s(1:12,1)) %employment rate
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Employment rate')
legend('EMP')
hold off
saveas(figure(21),[pwd '/plots/jko/lp3_v5_umshock.png']);
figure(22)
cla 
plot(quarters, IRF3_x4_s(1:12,1)) %ffr
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('Federal Funds rate')
legend('FFR')
hold off
saveas(figure(22),[pwd '/plots/jko/lp3_v6_umshock.png']);
figure(23)
cla 
plot(quarters, IRF3_x5_s(1:12,1)) %tbill
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Tbill yield')
legend('Tbill yield')
hold off
saveas(figure(23),[pwd '/plots/jko/lp3_v7_umshock.png']);
figure(24)
cla 
plot(quarters, IRF3_uf_s(1:12,1)) %financial uncertainty
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Financial uncertainty')
legend('Financial uncertainty')
hold off
saveas(figure(24),[pwd '/plots/jko/lp3_v8_umshock.png']);



%% Test VAR 4.0 w/JLN uncertainty but no inequality %%
%let the optimal lag length be the same as in VAR 1.0  
% parameters 
p = 1;  %number of lags
n = 7;  %number of vars 
N = length(um_q)-1; %update N

%% Compute IRFs via LP %%
 %% IRFs via 13 OLS regressions
 trend = cumsum(ones(N,1));
% Local projection
for i = 1:H+1 % 0 to H
    X1 = [ones(N-i,1) trend(1:N-i,1) um_q(1:N-i,1)] ;
    %X2 = [ones(N-i,1) trend(2:N-i+1) ratio(1:N-i,:)] ;
    X3 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) x1(1:N-i,:)] ;
    X4 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) x1(1:N-i,:) x2(1:N-i,:)] ;
    X5 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:)] ;
    X6 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:)] ;
    X7 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:) x5(1:N-i,:)] ;
    X8 = [ones(N-i,1) trend(1:N-i,1) um_q(2:N-i+1) x1(1:N-i,:) x2(1:N-i,:) x3(1:N-i,:) x4(1:N-i,:) x5(1:N-i,:) uf_q(1:N-i,:)] ; % matrix of regressors
    Y1 = [um_q(i:N-1,:)]; % resize Y
    %Y2 = [ratio(i+1:N,:)];
    Y3 = [x1(i+1:N,:)];
    Y4 = [x2(i+1:N,:)];
    Y5 = [x3(i+1:N,:)];
    Y6 = [x4(i+1:N,:)];
    Y7 = [x5(i+1:N,:)];
    Y8 = [uf_q(i+1:N,:)];
    beta4um(i,:)= X1\Y1; % record OLS estimators
    %beta3ratio(i,:)= X2\Y2;
    beta4x1(i,:)= X3\Y3;
    beta4x2(i,:)= X4\Y4;
    beta4x3(i,:)= X5\Y5;
    beta4x4(i,:)= X6\Y6;
    beta4x5(i,:)= X7\Y7;
    beta4uf(i,:)= X8\Y8;
end

% Normailize IRFs by size of the shock
%so that the IRFs capture the response of a 1% positive shock
IRF4_um = beta4um(1,3)\beta4um(:,3);%shock is 3rd in the matrix
%IRF3_ratio = beta3um(1,3)\beta3ratio(:,3);
IRF4_x1 = beta4um(1,3)\beta4x1(:,3);
IRF4_x2 = beta4um(1,3)\beta4x2(:,3);
IRF4_x3 = beta4um(1,3)\beta4x3(:,3);
IRF4_x4 = beta4um(1,3)\beta4x4(:,3);
IRF4_x5 = beta4um(1,3)\beta4x5(:,3);
IRF4_uf = beta4um(1,3)\beta4uf(:,3);

% smooth IRF to shocks
IRF4_um_s = [IRF4_um(1); zeros(H-1,1); IRF4_um(end)];
%IRF3_ratio_s = [IRF3_ratio(1); zeros(H-1,1); IRF3_ratio(end)];
IRF4_x1_s = [IRF4_x1(1); zeros(H-1,1); IRF4_x1(end)];
IRF4_x2_s = [IRF4_x2(1); zeros(H-1,1); IRF4_x2(end)];
IRF4_x3_s = [IRF4_x3(1); zeros(H-1,1); IRF4_x3(end)];
IRF4_x4_s = [IRF4_x4(1); zeros(H-1,1); IRF4_x4(end)];
IRF4_x5_s = [IRF4_x5(1); zeros(H-1,1); IRF4_x5(end)];
IRF4_uf_s = [IRF4_uf(1); zeros(H-1,1); IRF4_uf(end)];
for i = 2:H
IRF4_um_s(i) = mean(IRF4_um(i-1:i+1));
%IRF3_ratio_s(i) = mean(IRF3_ratio(i-1:i+1));
IRF4_x1_s(i) = mean(IRF4_x1(i-1:i+1));
IRF4_x2_s(i) = mean(IRF4_x2(i-1:i+1));
IRF4_x3_s(i) = mean(IRF4_x3(i-1:i+1));
IRF4_x4_s(i) = mean(IRF4_x4(i-1:i+1));
IRF4_x5_s(i) = mean(IRF4_x5(i-1:i+1));
IRF4_uf_s(i) = mean(IRF4_uf(i-1:i+1));
end


%plot individual irfs smoothed
figure(25)
cla 
plot(quarters, IRF4_um_s(1:12,1)) %macro uncertainty
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Macro uncertainty')
legend('Macro uncertainty')
hold off
saveas(figure(25),[pwd '/plots/jko/lp4_v1_umshock.png']);

figure(26)
cla 
plot(quarters, IRF4_x1_s(1:12,1)) %gdp growth
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized GDP growth')
legend('GDP')
hold off
saveas(figure(26),[pwd '/plots/jko/lp4_v2_umshock.png']);
figure(27)
cla 
plot(quarters, IRF4_x2_s(1:12,1)) %inflation rate
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Annualized Inflation')
legend('PCE')
hold off
saveas(figure(27),[pwd '/plots/jko/lp4_v3_umshock.png']);
figure(28)
cla 
plot(quarters, IRF4_x3_s(1:12,1)) %employment rate
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Employment rate')
legend('EMP')
hold off
saveas(figure(28),[pwd '/plots/jko/lp4_v4_umshock.png']);
figure(29)
cla 
plot(quarters, IRF4_x4_s(1:12,1)) %ffr
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('Federal Funds rate')
legend('FFR')
hold off
saveas(figure(29),[pwd '/plots/jko/lp4_v5_umshock.png']);
figure(30)
cla 
plot(quarters, IRF4_x5_s(1:12,1)) %tbill
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Tbill yield')
legend('Tbill yield')
hold off
saveas(figure(30),[pwd '/plots/jko/lp4_v6_umshock.png']);
figure(31)
cla 
plot(quarters, IRF4_uf_s(1:12,1)) %financial uncertainty
title('IRF: Smoothed response to a 1% Macro Uncertainty Shock')
xlabel('Time in quarters')
ylabel('% deviation Financial uncertainty')
legend('Financial uncertainty')
hold off
saveas(figure(31),[pwd '/plots/jko/lp4_v7_umshock.png']);
